### ISSUE TITLE
Case where name is false on button box

### ISSUE THREAD

**Issue by gdgellatly** [gityopie/odoo-addons#9]
@gityopie 

I just ran into this issue.  Not sure best way of handling it.  In the case where name is false, the map button doesn't quite work.  It just opens a big map not centred on the partner.  Also name isn't a unique field either.  We use a custom _compute_display_name which means I just changed context to {'search_default_name': name} or street and it worked fine.  But it will probably need a more general solution which would involve passing lat, long instead if they exist unless the intention was to open all partners with that name from that button.

**Comment by gityopie** [comment]
Hi @gdgellatly 

For me, the workaround to fix the issue by using `id` into `{'search_default_id': active_id}` instead of `name`
It will take extra code to make it work (in your `search` view you need to append field `id`).
Using geolocation fields: `lat` and `lng` also a good solution but I think this information is not unique either.

Thanks
